# Oldworld

# Semantic
background              #161617
foreground              #c9c7cd

# Selection
selection_background    #f5e0dc

# Cursor
cursor                  #f39967

# URL
url_color               #92a2d5

# Tabs
tab_bar_background      #161617

inactive_tab_foreground #c9c7cd
inactive_tab_background #1b1b1c

active_tab_foreground   #27272a
active_tab_background   #92a2d5

# Macos
macos_titlebar_color   #18181a

# Black
color0 #27272a
color8 #27272a

# Red
color1 #ea83a5
color9 #ea83a5

# Green
color2  #90b99f
color10 #90b99f

# Yellow
color3  #e6b99d
color11 #e6b99d

# Blue
color4  #92a2d5
color12 #92a2d5

# Magenta
color5  #e29eca
color13 #e29eca

# Cyan
color6  #85b5ba 
color14 #85b5ba

# White
color7  #c9c7cd
color15 #c9c7cd
